enabled: true
additional_trustees:
  - nvidia_employee_gh_username_1
  - nvidia_employee_gh_username_2
  - non_nvidia_employee_gh_username_1 # non NVIDIA employees on this list are ignored
additional_vetters:
  - nvidia_employee_gh_username_3
  - nvidia_employee_gh_username_4
  - non_nvidia_employee_gh_username_2 # non NVIDIA employees on this list are ignored
auto_sync_draft: false
auto_sync_ready: true
