name: Docker Build and Test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: linux-amd64-cpu16

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: nemo-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run tests in Docker container
      run: |
        docker run nemo-test:latest pytest 
