name: Docker Build and Test

on:
  push:
    branches:
      - "main"
      - "pull-request/[0-9]+"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run linting
      run: |
        pip install flake8
        flake8 .

  test:
    runs-on: linux-amd64-cpu16
    needs: lint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: nemo-test:latest
        cache-from: |
          type=gha,scope=${{ github.workflow }}
          type=gha,scope=${{ github.workflow }},ref=refs/heads/main
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}

    - name: Run tests in Docker container
      run: |
        docker run nemo-test:latest pytest 
